[mypy]
python_version = 3.11
cache_dir = .mypy_cache
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
no_implicit_optional = True
explicit_package_bases = True
mypy_path = src:HoustonPatchbay/source
# ignore_missing_imports = True
